# Autogenerated wrapper script for TVM_jll for aarch64-apple-darwin-llvm_version+15
export libtvm, libtvm_runtime

using Zlib_jll
using XML2_jll
using libLLVM_jll
using TVMFFI_jll
JLLWrappers.@generate_wrapper_header("TVM")
JLLWrappers.@declare_library_product(libtvm, "@rpath/libtvm.dylib")
JLLWrappers.@declare_library_product(libtvm_runtime, "@rpath/libtvm_runtime.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, XML2_jll, libLLVM_jll, TVMFFI_jll)
    JLLWrappers.@init_library_product(
        libtvm,
        "lib/libtvm.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtvm_runtime,
        "lib/libtvm_runtime.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
