# Autogenerated wrapper script for TVM_jll for aarch64-apple-darwin-llvm_version+20.asserts
export libtvm

using Zlib_jll
using XML2_jll
using libLLVM_jll
using TVMFFI_jll
JLLWrappers.@generate_wrapper_header("TVM")
JLLWrappers.@declare_library_product(libtvm, "@rpath/libtvm.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, XML2_jll, libLLVM_jll, TVMFFI_jll)
    JLLWrappers.@init_library_product(
        libtvm,
        "lib/libtvm.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
