# Autogenerated wrapper script for TVM_jll for i686-linux-gnu-cxx11-llvm_version+18.asserts
export libtvm, libtvm_runtime

using Zlib_jll
using XML2_jll
using libLLVM_jll
using TVMFFI_jll
JLLWrappers.@generate_wrapper_header("TVM")
JLLWrappers.@declare_library_product(libtvm, "libtvm.so")
JLLWrappers.@declare_library_product(libtvm_runtime, "libtvm_runtime.so")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, XML2_jll, libLLVM_jll, TVMFFI_jll)
    JLLWrappers.@init_library_product(
        libtvm,
        "lib/libtvm.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libtvm_runtime,
        "lib/libtvm_runtime.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
